server:
  port: 9000
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/edwin/Documents/Servicio de configuracion
  security:
    user:
      name: ${CONFIG_NAME}
      password: ${CONFIG_PASSWORD}



